version: "3.9"

services:
  quotes:
    image: quotes:dev        # 👈 明确给开发镜像命名
    build: .
    container_name: quotes_dev

    ports:
      - "5000:5000"

    volumes:
      # 🔥 代码实时同步（开发核心）
      - .:/app

      # 📦 数据持久化
      - ./data:/app/data

    environment:
      - FLASK_ENV=development
      - ADMIN_USER=myadmin       # 自定义账号
      - ADMIN_PASS=mypassword123
      - FLASK_SECRET_KEY=j8s9d8s7f987sdf98s7d9f87sd9f87s

    restart: unless-stopped
