version: "3.9"

services:
  quotes:
    image: quotes:prod
    container_name: quotes_prod

    ports:
      - "5000:5000"

    volumes:
      # ❗只挂载数据，不挂载代码
      - ./data:/app/data

    environment:
      - FLASK_ENV=production
      - ADMIN_USER=myadmin       # 自定义账号
      - ADMIN_PASS=mypassword123
      - FLASK_SECRET_KEY=j8s9d8s7f987sdf98s7d9f87sd9f87s

    restart: unless-stopped
